### ISSUE TITLE
FMN sends messages sometimes in digest, sometimes individual to scm-commits list

### ISSUE THREAD

**Issue by pnemade** [fedora-infra/fmn.rules#58]
Today, I saw that randomly fmn is sending messages to scm-commits list either in digest form or individually per email.

e.g.
See messages at same time sent as individual email
https://lists.fedoraproject.org/archives/list/scm-commits%40lists.fedoraproject.org/thread/GSR4W7EFCGYGAE6LKOMCCSMKD6L7MZW2/
https://lists.fedoraproject.org/archives/list/scm-commits%40lists.fedoraproject.org/thread/NXNY47UP74IYQINGCIIIMUBBETHEXDSA/

whereas some others together in digest as
https://lists.fedoraproject.org/archives/list/scm-commits%40lists.fedoraproject.org/thread/5BYOI2FQOWY54I66E6DLGCLU7WK4LRQC/

I think digest mode should be used when almost all messages are sent at same time. I am observing this since last 2 hours as of now.

**Comment by pnemade** [comment]
Good to follow same kind of message delivery. Either all be sent as digests periodically or individuals.

**Comment by ralphbean** [comment]
For the record, there are *two* FMN accounts sending email to the scm-commits list, which caused me some confusion:

- https://apps.fedoraproject.org/notifications/fmnscmcommits.id.fedoraproject.org/email/
- https://apps.fedoraproject.org/notifications/fmnpkgdbscmcommits.id.fedoraproject.org/email/

The first account is sending scm commits **and** pkgdb notifications, unbatched.

The second account is sending on pkgdb notifications, batched over a two-minute period.

**Comment by ralphbean** [comment]
OK, as discussed on IRC - I just disabled the **second** pkgdb batched account, leaving only the first account active.  It is sending pkgdb **and** scm messages both of which are **unbatched**.  Thanks all!
