### ISSUE TITLE
Time-out when adding social-media email list irc filter?

### ISSUE THREAD

**Issue by decause** [fedora-infra/fmn.rules#74]
https://apps.fedoraproject.org/notifications/decause.id.fedoraproject.org/irc/43816/

![Uploading Screenshot from 2016-03-16 17-23-03.png…]()

Can provide more details as requested.

**Comment by pypingou** [comment]
Looks like the screenshot didn't make it :)

**Comment by decause** [comment]
![screenshot from 2016-03-16 17-23-03](https://cloud.githubusercontent.com/assets/427420/14001066/9198dd82-f11a-11e5-881b-8ae2878e156a.png)

**Comment by ralphbean** [comment]
Yeah.. do you mean that it times out searching for example messages?

It's just not that smart :p  It doesn't know how to do a smart db query with a regex.. so it just queries for *all* messages and starts applying that pattern to everything returned until it gets something.

**Comment by jeremycline** [comment]
I've moved this to https://github.com/fedora-infra/fmn.web/issues/79 since it's a web UI issue.
